package com.tskforging.mtsandroid;

import android.app.AlertDialog;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.InputType;
import android.view.Gravity;
import android.view.KeyEvent;
import android.view.View;
import android.view.WindowManager;
import android.view.inputmethod.EditorInfo;
import android.view.inputmethod.InputMethodManager;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.GridLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.material.snackbar.Snackbar;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public final class MachineBoardActivity extends AppCompatActivity {
    private enum ScanMode { EMPLOYEE, ORDER, GREEN, YELLOW, TAG, BLADE }
    private static final int NAVY=Color.rgb(15,45,75),BLUE=Color.rgb(27,116,187),GREEN=Color.rgb(28,145,83),RED=Color.rgb(196,54,54),ORANGE=Color.rgb(230,145,40),GRAY=Color.rgb(105,115,125);
    private MultiMachineStore store; private SyncClient sync; private ConfigStore config; private SharedPreferences session;
    private LinearLayout body; private EditText scanBox; private String selectedGroup=MachineCatalog.CUTTING_1,selectedMachine="",employee="";
    private ScanMode scanMode=ScanMode.TAG; private String lastScanRaw="",pendingBladeReason=""; private long lastScanMs,pendingBladeLife;
    private final Handler handler=new Handler(Looper.getMainLooper()); private Runnable timerTask;

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);store=new MultiMachineStore(this);sync=new SyncClient(this,store);config=new ConfigStore(this);session=getSharedPreferences("mts_v2_session",MODE_PRIVATE);showBoard();}

    private void makeScreen(String title){stopTimer();ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(12),dp(12),dp(28));scroll.addView(body);setContentView(scroll);body.addView(text(title,24,NAVY,true));scanBox=new EditText(this);scanBox.setSingleLine(true);scanBox.setTextSize(14);scanBox.setShowSoftInputOnFocus(false);scanBox.setImeOptions(EditorInfo.IME_ACTION_DONE);scanBox.setHint("กด SCAN แล้วกด Enter");scanBox.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_DONE||(e!=null&&e.getKeyCode()==KeyEvent.KEYCODE_ENTER)){consumeScan();return true;}return false;});scanBox.setOnKeyListener((v,k,e)->{if(k==KeyEvent.KEYCODE_ENTER&&e.getAction()==KeyEvent.ACTION_UP){consumeScan();return true;}return false;});body.addView(scanBox,new LinearLayout.LayoutParams(-1,dp(48)));}

    private void showBoard(){selectedMachine="";employee="";makeScreen("MTS – สถานะเครื่องจักรทั้งหมด");body.addView(notice("เลือกเครื่องจักรก่อน แล้วสแกนพนักงานประจำเครื่อง",NAVY));Button attendance=outline("เช็คพนักงานประจำกะ (ไม่บังคับ)"+(session.getBoolean(attendanceKey()+"|done",false)?" ✓":""));attendance.setOnClickListener(v->attendanceDialog());body.addView(attendance);
        Spinner groups=choice(MachineCatalog.groups().toArray(new String[0]));groups.setSelection(Math.max(0,MachineCatalog.groups().indexOf(selectedGroup)));groups.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){String g=MachineCatalog.groups().get(pos);if(!g.equals(selectedGroup)){selectedGroup=g;showBoard();}}});body.addView(groups,new LinearLayout.LayoutParams(-1,dp(54)));body.addView(text("เขียว=ผลิต  น้ำเงิน=SET-UP  เหลือง=หยุดตามแผน  แดง=หยุดผิดปกติ  เทา=ไม่มีแผนการผลิต",13,Color.DKGRAY,false));
        GridLayout grid=new GridLayout(this);grid.setColumnCount(2);for(MultiMachineStore.MachineState s:store.states(selectedGroup)){Button b=machineButton(s);GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.height=dp(92);lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.setMargins(dp(4),dp(5),dp(4),dp(5));grid.addView(b,lp);}body.addView(grid);Button send=action("ส่งข้อมูลตอนนี้ • ค้างส่ง "+store.pendingCount()+" รายการ",BLUE);send.setOnClickListener(v->syncNow());body.addView(send);Button ip=outline("ตั้งค่า IP คอม: "+sync.serverUrl());ip.setOnClickListener(v->serverDialog());body.addView(ip);prepareScan(ScanMode.TAG);}
    private Button machineButton(MultiMachineStore.MachineState s){String line=s.machineId+"\n"+statusThai(s.status);String op=employeeForMachine(s.machineId);if(op.isEmpty()&&currentShift().equals(s.shiftName)&&!MultiMachineStore.CLOSED.equals(s.status))op=s.employee;if(!op.isEmpty())line+=" • "+op;if(!s.item.isEmpty())line+=" • "+s.item;if(!s.reason.isEmpty())line+="\n"+s.reason;if(isStopped(s.status)&&s.stopStartMs>0)line+=" • "+duration(totalStop(s,System.currentTimeMillis()));Button b=new Button(this);b.setText(line);b.setTextSize(13);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackgroundColor(statusColor(s.status));b.setOnClickListener(v->{selectedMachine=s.machineId;employee=currentEmployee();showMachine();});return b;}

    private void showMachine(){employee=currentEmployee();MultiMachineStore.MachineState s=store.state(selectedMachine);MachineCatalog.Machine mc=MachineCatalog.find(selectedMachine);MultiMachineStore.VerificationState vs=currentVerification();makeScreen(s.machineId+" • "+s.groupName);body.addView(text("พนักงาน: "+(employee.isEmpty()?"ยังไม่สแกน":employee)+"    กะ: "+currentShift(),16,employee.isEmpty()?RED:NAVY,true));Button emp=action(employee.isEmpty()?"1. สแกนพนักงานประจำเครื่อง":"เปลี่ยนพนักงานประจำเครื่อง",employee.isEmpty()?RED:BLUE);emp.setOnClickListener(v->prepareScan(ScanMode.EMPLOYEE));body.addView(emp);
        String needed=isCutting()?"Order → Tag เขียว → Tag เหลือง":"Order → Tag เหลือง";body.addView(statusCard("ตรวจสอบเอกสาร",verificationThai(vs.status)+" • "+needed));Button verify=action("2. "+nextVerificationLabel(vs),"PASS".equals(vs.status)?GREEN:BLUE);verify.setOnClickListener(v->beginVerification(vs));body.addView(verify);
        body.addView(statusCard("ตารางกะของเครื่องนี้",MultiMachineStore.scheduleName(scheduleType(s))));if(s.startMs>0&&!MultiMachineStore.CLOSED.equals(s.status)&&scheduleType(s)!=3){Button extend=outline("เปลี่ยนตารางเป็น OT แบบที่ 2");extend.setOnClickListener(v->saveSchedule(3));body.addView(extend);}
        body.addView(statusCard("สถานะ",statusThai(s.status)+(s.reason.isEmpty()?"":" • "+s.reason)));if(isStopped(s.status)&&s.stopStartMs>0)addLiveTimer(s);body.addView(statusCard("งานปัจจุบัน",s.item.isEmpty()?"ยังไม่มี WIP/FG Tag":s.item+" / "+s.partNo+" / Lot "+s.lot));body.addView(statusCard("ยอดสะสม",String.format(Locale.US,"OK %,d   NG %,d   Stop %s",s.ok,s.ng,duration(totalStop(s,System.currentTimeMillis())))));
        Button start=action("3. เริ่ม/กลับมาผลิต",GREEN);start.setOnClickListener(v->startMachine());body.addView(start);Button tag=action("4. สแกน WIP/FG Tag",BLUE);tag.setOnClickListener(v->prepareScan(ScanMode.TAG));body.addView(tag);Button stop=action("หยุดเครื่องจักร",RED);stop.setOnClickListener(v->stopMenu());body.addView(stop);Button close=action("ดูสรุปก่อนปิดกะ",RED);close.setOnClickListener(v->closeSummary());body.addView(close);Button back=outline("กลับหน้าเครื่องจักรทั้งหมด");back.setOnClickListener(v->showBoard());body.addView(back);prepareScan(employee.isEmpty()?ScanMode.EMPLOYEE:ScanMode.TAG);}

    private void attendanceDialog(){EditText total=input("พนักงานทั้งกะ (คน)",true),sick=input("ลาป่วย",true),personal=input("ลากิจ",true),vacation=input("ลาพักร้อน",true),outside=input("ไปทำงานข้างนอก",true),reason=input("เหตุผลที่ไปทำงานข้างนอก",false);LinearLayout box=dialogBox();box.addView(total);box.addView(sick);box.addView(personal);box.addView(vacation);box.addView(outside);box.addView(reason);AlertDialog d=new AlertDialog.Builder(this).setTitle("เช็คพนักงานกะ "+currentShift()).setMessage("รายการนี้ไม่บังคับ สามารถข้ามได้").setView(box).setNegativeButton("ยกเลิก",null).setPositiveButton("บันทึก",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{long o=num(outside);if(o>0&&reason.getText().toString().trim().isEmpty()){warning("กรุณาระบุเหตุผลพนักงานที่ไปทำงานข้างนอก");return;}try{long now=System.currentTimeMillis();store.recordAttendance(currentShift(),num(total),num(sick),num(personal),num(vacation),o,reason.getText().toString(),now);session.edit().putBoolean(attendanceKey()+"|done",true).apply();d.dismiss();toast("บันทึกพนักงานประจำกะแล้ว");syncData(false);showBoard();}catch(Exception e){warning(e.getMessage());}}));d.show();}

    private void beginVerification(MultiMachineStore.VerificationState v){if(!requireEmployee())return;if(v.orderRaw.isEmpty())prepareScan(ScanMode.ORDER);else if(isCutting()&&v.greenRaw.isEmpty())prepareScan(ScanMode.GREEN);else if(v.yellowRaw.isEmpty())prepareScan(ScanMode.YELLOW);else{store.saveVerificationScan(selectedMachine,v.shiftKey,"order","",System.currentTimeMillis());store.saveVerificationScan(selectedMachine,v.shiftKey,"green","",System.currentTimeMillis());store.saveVerificationScan(selectedMachine,v.shiftKey,"yellow","",System.currentTimeMillis());prepareScan(ScanMode.ORDER);}toast("ขั้นต่อไป: "+scanPrompt(scanMode)+" แล้วกด Enter");}
    private String nextVerificationLabel(MultiMachineStore.VerificationState v){if("PASS".equals(v.status))return "ตรวจผ่านแล้ว • กดเพื่อตรวจชุดใหม่";if(v.orderRaw.isEmpty())return "สแกนใบสั่งผลิต";if(isCutting()&&v.greenRaw.isEmpty())return "สแกน Tag เขียว";if(v.yellowRaw.isEmpty())return "สแกน Tag เหลือง";return "ตรวจใหม่";}
    private void confirmDocument(ScanMode mode,String raw){MaterialParser.Doc d=mode==ScanMode.ORDER?MaterialParser.order(raw):MaterialParser.tag(raw);if(!d.valid()){warning("รูปแบบ "+scanPrompt(mode)+" ไม่ถูกต้อง");return;}String info="Order: "+dash(d.order)+"\nMaterial: "+dash(d.materialItem)+"\nDetail: "+dash(d.detail)+"\nPart No.: "+dash(d.partNo)+"\nPart Name: "+dash(d.partName)+(mode==ScanMode.ORDER?"":"\nLot: "+dash(d.lot)+"\nCharge: "+dash(d.charge));new AlertDialog.Builder(this).setTitle("ยืนยัน "+scanPrompt(mode)).setMessage(info).setNegativeButton("สแกนใหม่",(x,w)->prepareScan(mode)).setPositiveButton("ยืนยัน",(x,w)->{String kind=mode==ScanMode.ORDER?"order":mode==ScanMode.GREEN?"green":"yellow";store.saveVerificationScan(selectedMachine,verificationKey(),kind,raw,System.currentTimeMillis());MultiMachineStore.VerificationState v=currentVerification();if(mode==ScanMode.ORDER){prepareScan(isCutting()?ScanMode.GREEN:ScanMode.YELLOW);toast("ยืนยันแล้ว • ขั้นต่อไป: "+scanPrompt(scanMode));}else if(mode==ScanMode.GREEN){prepareScan(ScanMode.YELLOW);toast("ยืนยันแล้ว • ขั้นต่อไป: สแกน Tag เหลือง");}else verifyDocuments(v);showMachine();}).show();}
    private void verifyDocuments(MultiMachineStore.VerificationState v){MaterialParser.Doc o=MaterialParser.order(v.orderRaw),g=MaterialParser.tag(v.greenRaw),y=MaterialParser.tag(v.yellowRaw);List<String> bad=new ArrayList<>();if(isCutting()){compare(bad,"Order No.",o.order,g.order);compare(bad,"Material",o.materialItem,g.materialItem);compare(bad,"Detail",o.detail,g.detail);compare(bad,"Part No.",o.partNo,g.partNo);compare(bad,"Part Name",o.partName,g.partName);compare(bad,"Green/Yellow Material",g.materialItem,y.materialItem);compare(bad,"Green/Yellow Detail",g.detail,y.detail);compare(bad,"Green/Yellow Weight",g.weight+g.weightUnit,y.weight+y.weightUnit);compare(bad,"Green/Yellow Qty",g.qty+g.qtyUnit,y.qty+y.qtyUnit);compare(bad,"Green/Yellow Charge",g.charge,y.charge);}else{compareIfBoth(bad,"Material",o.materialItem,y.materialItem);compareIfBoth(bad,"Part No.",o.partNo,y.partNo);compareIfBoth(bad,"Part Name",o.partName,y.partName);}
        boolean pass=bad.isEmpty();String message=pass?"ข้อมูลตรงกันครบ":String.join("\n",bad);try{store.saveVerificationResult(selectedMachine,v.shiftKey,pass,message,employee,currentShift(),System.currentTimeMillis());if(pass)toast("ตรวจผ่าน • ขั้นต่อไป: เลือกตารางกะและเริ่มผลิต");else warning("ตรวจไม่ผ่าน\n"+message);}catch(Exception e){warning(e.getMessage());}}

    private void startMachine(){if(!requireEmployee())return;MultiMachineStore.VerificationState v=currentVerification();if(!"PASS".equals(v.status)){warning("ยังตรวจเอกสารไม่ผ่าน กรุณาสแกน "+(isCutting()?"Order, Tag เขียว และ Tag เหลือง":"Order และ Tag เหลือง"));return;}MultiMachineStore.MachineState s=store.state(selectedMachine);boolean fresh=s.startMs<=0||MultiMachineStore.UNKNOWN.equals(s.status)||MultiMachineStore.CLOSED.equals(s.status)||!currentShift().equals(s.shiftName);if(fresh&&scheduleType(s)==0){chooseSchedule();return;}startWithTimeCheck(fresh);}
    private void chooseSchedule(){new AlertDialog.Builder(this).setTitle("เลือกตารางกะสำหรับ "+selectedMachine).setItems(new String[]{scheduleDescription(1),scheduleDescription(2)},(d,w)->{saveSchedule(w+1);startWithTimeCheck(true);}).setNegativeButton("ยกเลิก",null).show();}
    private void saveSchedule(int type){try{store.setSchedule(selectedMachine,type,employee,currentShift(),System.currentTimeMillis());session.edit().putInt(scheduleKey(),type).apply();toast("เลือก "+MultiMachineStore.scheduleName(type)+" แล้ว");showMachine();}catch(Exception e){warning(e.getMessage());}}
    private void startWithTimeCheck(boolean fresh){long actual=System.currentTimeMillis(),scheduled=scheduleTime(currentShift(),true,1,actual);if(fresh&&Math.abs(actual-scheduled)>config.startTolerance()*60000L){String[] base=config.startReasons(),items=new String[base.length+1];items[0]="กรุณาเลือกเหตุผล";System.arraycopy(base,0,items,1,base.length);Spinner reason=choice(items);AlertDialog d=new AlertDialog.Builder(this).setTitle("เริ่มกะนอกเวลามาตรฐาน").setMessage("ต้องเลือกเหตุผลก่อนเริ่มทำงาน").setView(reason).setNegativeButton("ยกเลิก",null).setPositiveButton("ยืนยัน",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(z->{if(reason.getSelectedItemPosition()==0){warning("กรุณาเลือกเหตุผล");return;}startNow(actual,actual,String.valueOf(reason.getSelectedItem()));d.dismiss();}));d.show();}else startNow(actual,fresh?scheduled:actual,"");}
    private void startNow(long actual,long effective,String reason){try{store.setStatus(selectedMachine,MultiMachineStore.RUNNING,reason,"",employee,currentShift(),actual,effective);afterEvent("เริ่มผลิตแล้ว","สแกน WIP/FG Tag เมื่อได้ชิ้นงาน");}catch(Exception e){warning(e.getMessage());}}

    private void stopMenu(){if(!requireEmployee())return;MultiMachineStore.MachineState s=store.state(selectedMachine);if(s.startMs<=0){warning("ต้องเริ่มกะก่อน จึงจะใช้เมนูหยุดเครื่องได้");return;}List<String> list=new ArrayList<>();list.add("ตั้งงานระหว่างผลิต");list.add("SET-UP / เปลี่ยนรุ่น");if(MachineCatalog.find(selectedMachine)!=null&&MachineCatalog.find(selectedMachine).bladeEnabled)list.add("เปลี่ยนใบเลื่อย");list.add("ไม่มีแผนการผลิต");list.add("ไม่มี OT");list.add("5S");list.add("รอวัตถุดิบ");list.add("ฝึกอบรม");list.add("ไม่มีพนักงาน");list.add("เครื่องจักรเสีย");list.add("ซ่อมบำรุง");new AlertDialog.Builder(this).setTitle("เลือกรายการหยุดเครื่อง").setItems(list.toArray(new String[0]),(d,w)->selectStop(list.get(w))).setNegativeButton("ยกเลิก",null).show();}
    private void selectStop(String reason){if(reason.equals("เปลี่ยนใบเลื่อย")){beginBladeChange();return;}if(reason.equals("เครื่องจักรเสีย")||reason.equals("ซ่อมบำรุง")){EditText detail=input("พิมพ์รายละเอียด",false);AlertDialog d=new AlertDialog.Builder(this).setTitle(reason).setView(detail).setNegativeButton("ยกเลิก",null).setPositiveButton("เริ่มนับเวลาหยุด",null).create();d.setOnShowListener(x->{detail.requestFocus();d.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(detail.getText().toString().trim().isEmpty()){warning("กรุณาพิมพ์รายละเอียด");return;}setStop(MultiMachineStore.UNPLANNED_STOP,reason,detail.getText().toString());d.dismiss();});});d.show();return;}String status=reason.startsWith("ตั้งงาน")||reason.startsWith("SET-UP")?MultiMachineStore.SETUP:MultiMachineStore.PLANNED_STOP;setStop(status,reason,"");}
    private void setStop(String status,String reason,String detail){try{store.setStatus(selectedMachine,status,reason,detail,employee,currentShift(),System.currentTimeMillis());afterEvent("เริ่มนับเวลาหยุดแล้ว","เมื่อพร้อม กด เริ่ม/กลับมาผลิต");}catch(Exception e){warning(e.getMessage());}}
    private void beginBladeChange(){MultiMachineStore.MachineState s=store.state(selectedMachine);try{store.setStatus(selectedMachine,MultiMachineStore.PLANNED_STOP,"เปลี่ยนใบเลื่อย","",employee,currentShift(),System.currentTimeMillis());}catch(Exception e){warning(e.getMessage());return;}EditText life=input("Tool Life ใบปัจจุบัน (จำนวนชิ้น)",true);Spinner reason=choice(new String[]{"ครบอายุ Tool","แตกหัก","บิ่น","คุณภาพผิดปกติ","อื่น ๆ"});LinearLayout box=dialogBox();box.addView(text("ใบปัจจุบัน: "+dash(s.bladeId),15,NAVY,true));box.addView(life);box.addView(reason);AlertDialog d=new AlertDialog.Builder(this).setTitle("ข้อมูลใบเลื่อยปัจจุบัน").setView(box).setNegativeButton("ยกเลิก",null).setPositiveButton("ไปสแกนใบใหม่",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(life.getText().toString().trim().isEmpty()){warning("กรุณาลง Tool Life เป็นจำนวนชิ้น");return;}pendingBladeLife=num(life);pendingBladeReason=String.valueOf(reason.getSelectedItem());d.dismiss();prepareScan(ScanMode.BLADE);toast("ขั้นต่อไป: สแกนใบเลื่อยใหม่ แล้วกด Enter");}));d.show();}

    private void confirmResultTag(String raw){TagParser.ResultTag tag=TagParser.parse(raw);if(!tag.isValid()){warning("ไม่ใช่ WIP/FG Tag ที่รองรับ");return;}String mismatch=checkResultTag(tag);if(!mismatch.isEmpty()){warning("Tag ไม่ตรงกับงานที่ตรวจไว้\n"+mismatch);return;}EditText ng=input("จำนวนงานเสีย NG",true);Spinner reason=choice(config.ngReasons());LinearLayout box=dialogBox();box.addView(text("Order: "+dash(tag.order)+"\nProcess: "+tag.process+"\nItem: "+tag.item+"\nPart No.: "+dash(tag.partNo)+"\nLot: "+tag.lot+"\nTag Qty: "+tag.qty,15,NAVY,true));box.addView(ng);box.addView(text("ถ้า NG มากกว่า 0 ให้เลือกสาเหตุ",13,NAVY,false));box.addView(reason);AlertDialog d=new AlertDialog.Builder(this).setTitle("ยืนยัน WIP/FG Tag").setView(box).setNegativeButton("สแกนใหม่",null).setPositiveButton("บันทึก",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{long bad=num(ng);try{MultiMachineStore.TagResult r=store.recordTag(selectedMachine,employee,currentShift(),tag,bad,bad>0?String.valueOf(reason.getSelectedItem()):"",System.currentTimeMillis());if(!r.accepted){warning(r.message);return;}d.dismiss();new AlertDialog.Builder(this).setTitle("บันทึก Tag สำเร็จ").setMessage("OK "+r.thisShiftQty+" / NG "+r.ngQty+"\nTag Qty "+r.tagQty+"\nPrevious "+r.previousQty+"\n\nขั้นต่อไป: ผลิตต่อ หรือเลือกหยุดเครื่อง").setPositiveButton("รับทราบ",(a,b)->showMachine()).show();syncData(false);}catch(Exception e){warning(e.getMessage());}}));d.show();}
    private String checkResultTag(TagParser.ResultTag t){MultiMachineStore.VerificationState v=currentVerification();if(!"PASS".equals(v.status))return "ยังไม่ได้ตรวจเอกสาร";MaterialParser.Doc o=MaterialParser.order(v.orderRaw),y=MaterialParser.tag(v.yellowRaw);List<String> bad=new ArrayList<>();compareIfBoth(bad,"Order",o.order,t.order);compareIfBoth(bad,"Item",o.materialItem,t.item);compareIfBoth(bad,"Part No.",!o.partNo.isEmpty()?o.partNo:y.partNo,t.partNo);compareIfBoth(bad,"Lot",y.lot,t.lot);compareIfBoth(bad,"Charge",y.charge,t.charge);return String.join("\n",bad);}

    private void closeSummary(){if(!requireEmployee())return;MultiMachineStore.MachineState s=store.state(selectedMachine);if(s.startMs<=0){warning("ยังไม่ได้เริ่มกะ");return;}int type=scheduleType(s);long now=System.currentTimeMillis(),stop=totalStop(s,now),standard=standardSeconds(type),elapsed=Math.max(0,(Math.min(now,scheduleTime(currentShift(),false,type,now))-s.startMs)/1000),work=Math.max(0,Math.min(standard,elapsed)-stop);String msg="เครื่อง: "+s.machineId+"\nพนักงาน: "+employee+"\nกะ: "+currentShift()+" • "+MultiMachineStore.scheduleName(type)+"\nเริ่ม: "+dateTime(s.startMs)+"\nWorking time (ก่อนหักเวลาพัก): "+duration(work)+"\nStop time: "+duration(stop)+"\nOK: "+s.ok+"  NG: "+s.ng;if(isStopped(s.status))msg+="\n\nระบบจะตัดเวลาหยุดปัจจุบันให้อัตโนมัติ";new AlertDialog.Builder(this).setTitle("สรุปงานก่อนปิดกะ").setMessage(msg).setNegativeButton("กลับไปตรวจสอบ",null).setPositiveButton("กรอกข้อมูลปิดกะ",(d,w)->closeDialog()).show();}
    private void closeDialog(){EditText ok=input("Last Lot OK",true),ng=input("Last Lot NG",true);Spinner reason=choice(prepend("ไม่มี NG",config.ngReasons())),coffee=choice(new String[]{"เลือกจำนวนพักกาแฟ","0 ครั้ง","1 ครั้ง","2 ครั้ง"}),meal=choice(new String[]{"เลือกการพักอาหาร","ไม่ได้พัก","พัก"}),ot=choice(new String[]{"เลือกการพัก OT","ไม่ได้พัก","พัก"});LinearLayout box=dialogBox();box.addView(ok);box.addView(ng);box.addView(reason);box.addView(coffee);box.addView(meal);box.addView(ot);AlertDialog d=new AlertDialog.Builder(this).setTitle("ปิดกะ "+selectedMachine).setView(box).setNegativeButton("ยกเลิก",null).setPositiveButton("ยืนยันปิดกะ",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(num(ng)>0&&reason.getSelectedItemPosition()==0){warning("กรุณาเลือกสาเหตุ NG");return;}if(coffee.getSelectedItemPosition()==0||meal.getSelectedItemPosition()==0||ot.getSelectedItemPosition()==0){warning("กรุณาตอบข้อมูลการพักให้ครบ");return;}long actual=System.currentTimeMillis();int type=scheduleType(store.state(selectedMachine));long planned=scheduleTime(currentShift(),false,type,actual),effective=actual;boolean early=actual<planned-config.closeEarlyTolerance()*60000L;if(!early&&Math.abs(actual-planned)<=config.closeEarlyTolerance()*60000L)effective=planned;if(early){d.dismiss();closeReasonDialog(ok,ng,reason,coffee.getSelectedItemPosition()-1,meal.getSelectedItemPosition()==2,ot.getSelectedItemPosition()==2,actual,effective);return;}finishClose(ok,ng,reason,coffee.getSelectedItemPosition()-1,meal.getSelectedItemPosition()==2,ot.getSelectedItemPosition()==2,actual,effective,"");d.dismiss();}));d.show();}
    private void closeReasonDialog(EditText ok,EditText ng,Spinner reason,int coffee,boolean meal,boolean ot,long actual,long effective){Spinner why=choice(config.closeReasons());new AlertDialog.Builder(this).setTitle("ปิดก่อนเวลา ต้องระบุสาเหตุ").setView(why).setNegativeButton("ยกเลิก",null).setPositiveButton("ยืนยัน",(d,w)->finishClose(ok,ng,reason,coffee,meal,ot,actual,effective,String.valueOf(why.getSelectedItem()))).show();}
    private void finishClose(EditText ok,EditText ng,Spinner reason,int coffee,boolean meal,boolean ot,long actual,long effective,String closeReason){try{int type=scheduleType(store.state(selectedMachine));store.closeMachine(selectedMachine,num(ok),num(ng),num(ng)>0?String.valueOf(reason.getSelectedItem()):"",coffee,meal,ot,employee,currentShift(),actual,effective,closeReason,config.coffeeMinutes(),config.mealMinutes(),config.otBreakMinutes(),standardSeconds(type));toast("ปิดกะแล้ว • ขั้นต่อไป: เลือกเครื่องจักรเครื่องถัดไป");syncData(false);showBoard();}catch(Exception e){warning(e.getMessage());}}

    private void prepareScan(ScanMode mode){if(mode==ScanMode.EMPLOYEE&&selectedMachine.isEmpty()){warning("กรุณาเลือกเครื่องจักรก่อน");return;}scanMode=mode;if(scanBox!=null){scanBox.setText("");scanBox.setHint(scanPrompt(mode)+" แล้วกด Enter");scanBox.requestFocus();}}
    private String scanPrompt(ScanMode m){if(m==ScanMode.EMPLOYEE)return "สแกนพนักงาน";if(m==ScanMode.ORDER)return "สแกนใบสั่งผลิต";if(m==ScanMode.GREEN)return "สแกน Tag เขียว";if(m==ScanMode.YELLOW)return "สแกน Tag เหลือง";if(m==ScanMode.BLADE)return "สแกนใบเลื่อยใหม่";return "สแกน WIP/FG Tag";}
    private void consumeScan(){String raw=scanBox.getText().toString().trim();scanBox.setText("");if(!raw.isEmpty())handleScan(raw);}
    private void handleScan(String raw){long now=System.currentTimeMillis();if(raw.equals(lastScanRaw)&&now-lastScanMs<500)return;lastScanRaw=raw;lastScanMs=now;if(selectedMachine.isEmpty()){warning("กรุณาเลือกเครื่องจักรก่อนสแกน");return;}if(scanMode==ScanMode.EMPLOYEE){String name=identity(raw,"EMP");if(name.isEmpty()){warning("QR พนักงานไม่มีชื่อหรือรหัส");return;}new AlertDialog.Builder(this).setTitle("ยืนยันพนักงาน").setMessage("เครื่อง: "+selectedMachine+"\nพนักงาน: "+name+"\nกะ: "+currentShift()).setNegativeButton("สแกนใหม่",null).setPositiveButton("ยืนยัน",(d,w)->{try{employee=name;session.edit().putString(employeeKey(selectedMachine),name).apply();store.assignEmployee(selectedMachine,name,currentShift(),System.currentTimeMillis());toast("ยืนยันพนักงานแล้ว • ขั้นต่อไป: ตรวจสอบเอกสาร");syncData(false);showMachine();}catch(Exception e){warning(e.getMessage());}}).show();return;}if(!requireEmployee())return;if(scanMode==ScanMode.ORDER||scanMode==ScanMode.GREEN||scanMode==ScanMode.YELLOW){confirmDocument(scanMode,raw);return;}if(scanMode==ScanMode.BLADE){String blade=identity(raw,"BLADE");MultiMachineStore.MachineState s=store.state(selectedMachine);new AlertDialog.Builder(this).setTitle("ยืนยันเปลี่ยนใบเลื่อย").setMessage("ใบเดิม: "+dash(s.bladeId)+"\nTool Life: "+pendingBladeLife+" ชิ้น\nเหตุผล: "+pendingBladeReason+"\nใบใหม่: "+blade).setNegativeButton("สแกนใหม่",null).setPositiveButton("ยืนยัน",(d,w)->{try{store.changeBlade(selectedMachine,blade,pendingBladeLife,pendingBladeReason,employee,currentShift(),System.currentTimeMillis());pendingBladeReason="";pendingBladeLife=0;afterEvent("บันทึกใบเลื่อยใหม่แล้ว","กด เริ่ม/กลับมาผลิต");}catch(Exception e){warning(e.getMessage());}}).show();return;}confirmResultTag(raw);}

    private MultiMachineStore.VerificationState currentVerification(){return store.verification(selectedMachine,verificationKey());}
    private String verificationKey(){return MultiMachineStore.shiftKey(currentShift(),System.currentTimeMillis());}
    private boolean isCutting(){MachineCatalog.Machine m=MachineCatalog.find(selectedMachine);return m!=null&&(MachineCatalog.CUTTING_1.equals(m.group)||MachineCatalog.CUTTING_2.equals(m.group));}
    private int scheduleType(MultiMachineStore.MachineState s){int saved=session.getInt(scheduleKey(),0);if(saved>0)return saved;return currentShift().equals(s.shiftName)&&s.startMs>0&&!MultiMachineStore.CLOSED.equals(s.status)?s.scheduleType:0;}
    private String scheduleKey(){return "schedule|"+selectedMachine+"|"+verificationKey();}
    private String attendanceKey(){return "attendance|"+verificationKey();}
    private String scheduleDescription(int type){return MultiMachineStore.scheduleName(type)+("DAY".equals(currentShift())?(type==1?" • 08:00–17:00":" • 08:00–19:20"):(type==1?" • 20:00–05:00":" • 20:00–07:20"));}
    private long standardSeconds(int type){return type==1?9*3600L:type==2?(11*3600L+20*60L):(12*3600L+20*60L);}
    private long scheduleTime(String shift,boolean start,int type,long now){String hm;if(start)hm="DAY".equals(shift)?"08:00":"20:00";else if(type==1)hm="DAY".equals(shift)?"17:00":"05:00";else if(type==2)hm="DAY".equals(shift)?"19:20":"07:20";else hm="DAY".equals(shift)?"20:20":"08:20";String[] p=hm.split(":");Calendar c=Calendar.getInstance();c.setTimeInMillis(now);c.set(Calendar.HOUR_OF_DAY,Integer.parseInt(p[0]));c.set(Calendar.MINUTE,Integer.parseInt(p[1]));c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);if("NIGHT".equals(shift)){if(start&&c.getTimeInMillis()-now>12*3600000L)c.add(Calendar.DAY_OF_MONTH,-1);if(!start&&now-c.getTimeInMillis()>12*3600000L)c.add(Calendar.DAY_OF_MONTH,1);}return c.getTimeInMillis();}
    private String currentShift(){Calendar c=Calendar.getInstance();int m=c.get(Calendar.HOUR_OF_DAY)*60+c.get(Calendar.MINUTE);return m>=8*60&&m<20*60?"DAY":"NIGHT";}
    private String currentEmployee(){employee=employeeForMachine(selectedMachine);if(employee.isEmpty()&&!selectedMachine.isEmpty()){MultiMachineStore.MachineState s=store.state(selectedMachine);if(currentShift().equals(s.shiftName)&&!MultiMachineStore.CLOSED.equals(s.status))employee=s.employee;}return employee;}
    private String employeeForMachine(String id){return id.isEmpty()?"":session.getString(employeeKey(id),"").trim();}
    private String employeeKey(String id){return "employee|"+id+"|"+verificationKey();}
    private boolean requireEmployee(){if(selectedMachine.isEmpty()){warning("กรุณาเลือกเครื่องจักรก่อน");return false;}employee=currentEmployee();if(!employee.isEmpty())return true;warning("ยังไม่ได้สแกนพนักงานสำหรับเครื่อง "+selectedMachine);prepareScan(ScanMode.EMPLOYEE);return false;}

    private void addLiveTimer(MultiMachineStore.MachineState initial){TextView timer=statusCard("กำลังนับเวลาหยุด","-");timer.setTextColor(RED);body.addView(timer);String id=initial.machineId;timerTask=new Runnable(){public void run(){if(!id.equals(selectedMachine))return;MultiMachineStore.MachineState s=store.state(id);if(!isStopped(s.status)||s.stopStartMs<=0)return;timer.setText("กำลังนับเวลาหยุด\nครั้งนี้ "+duration(Math.max(0,(System.currentTimeMillis()-s.stopStartMs)/1000))+"   สะสม "+duration(totalStop(s,System.currentTimeMillis()))+"\nเหตุผล: "+s.reason+(s.detail.isEmpty()?"":" • "+s.detail));handler.postDelayed(this,1000);}};handler.post(timerTask);}
    private void stopTimer(){if(timerTask!=null){handler.removeCallbacks(timerTask);timerTask=null;}}
    private void syncNow(){syncData(true);} private void syncData(boolean notify){sync.flush((sent,pending,error)->{if(notify){if(error.isEmpty())toast("ส่งแล้ว "+sent+" • ค้าง "+pending);else warning("ส่งไม่สำเร็จ เก็บ Offline ไว้แล้ว • ค้าง "+pending+" • "+error);}if(body!=null&&selectedMachine.isEmpty())showBoard();});}
    private void afterEvent(String message,String next){toast(message+"\nขั้นต่อไป: "+next);syncData(false);showMachine();}
    private void serverDialog(){EditText e=input("http://192.168.18.145:8765",false);e.setText(sync.serverUrl());new AlertDialog.Builder(this).setTitle("ที่อยู่โปรแกรมรับข้อมูล").setView(e).setNegativeButton("ยกเลิก",null).setPositiveButton("บันทึก",(d,w)->{sync.setServerUrl(e.getText().toString());showBoard();}).show();}
    private static void compare(List<String> bad,String name,String a,String b){if(!MaterialParser.norm(a).equals(MaterialParser.norm(b)))bad.add("✕ "+name+" ["+a+"] ≠ ["+b+"]");}
    private static void compareIfBoth(List<String> bad,String name,String a,String b){if(!a.trim().isEmpty()&&!b.trim().isEmpty())compare(bad,name,a,b);}
    private static String[] prepend(String first,String[] rest){String[] out=new String[rest.length+1];out[0]=first;System.arraycopy(rest,0,out,1,rest.length);return out;}
    private static String identity(String raw,String prefix){String s=raw==null?"":raw.trim();String[] f=s.split("\\|",-1);return f.length>1&&f[0].equalsIgnoreCase(prefix)?f[1].trim():s;}
    private static boolean isStopped(String s){return MultiMachineStore.SETUP.equals(s)||MultiMachineStore.PLANNED_STOP.equals(s)||MultiMachineStore.UNPLANNED_STOP.equals(s);}
    private static long totalStop(MultiMachineStore.MachineState s,long now){return s.stopSec+(s.stopStartMs>0?Math.max(0,(now-s.stopStartMs)/1000):0);}
    private static String statusThai(String s){if(MultiMachineStore.RUNNING.equals(s))return "กำลังผลิต";if(MultiMachineStore.SETUP.equals(s))return "SET-UP/ตั้งงาน";if(MultiMachineStore.PLANNED_STOP.equals(s))return "หยุดตามแผน";if(MultiMachineStore.UNPLANNED_STOP.equals(s))return "หยุดผิดปกติ";if(MultiMachineStore.CLOSED.equals(s))return "ปิดกะแล้ว";return "ไม่มีแผนการผลิต";}
    private static String verificationThai(String s){return "PASS".equals(s)?"ผ่าน":"FAIL".equals(s)?"ไม่ผ่าน":"ยังไม่ครบ";}
    private static int statusColor(String s){if(MultiMachineStore.RUNNING.equals(s))return GREEN;if(MultiMachineStore.SETUP.equals(s))return BLUE;if(MultiMachineStore.PLANNED_STOP.equals(s))return ORANGE;if(MultiMachineStore.UNPLANNED_STOP.equals(s))return RED;return GRAY;}
    private static String duration(long sec){sec=Math.max(0,sec);return String.format(Locale.US,"%02d:%02d:%02d",sec/3600,(sec%3600)/60,sec%60);}
    private static String dateTime(long ms){return ms<=0?"-":new SimpleDateFormat("dd/MM/yyyy HH:mm",Locale.US).format(new Date(ms));}
    private static String dash(String s){return s==null||s.trim().isEmpty()?"-":s.trim();}
    private long num(EditText e){try{return Long.parseLong(e.getText().toString().trim());}catch(Exception x){return 0;}}
    private void toast(String s){Toast.makeText(this,s==null?"ผิดพลาด":s,Toast.LENGTH_LONG).show();}
    private void warning(String s){String m=s==null||s.trim().isEmpty()?"เกิดข้อผิดพลาด":s;if(body!=null)Snackbar.make(body,m,Snackbar.LENGTH_LONG).setBackgroundTint(RED).setTextColor(Color.WHITE).show();else toast(m);}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(dp(4),dp(6),dp(4),dp(6));if(bold)t.setTypeface(null,android.graphics.Typeface.BOLD);return t;}
    private TextView statusCard(String title,String value){TextView t=text(title+"\n"+value,16,NAVY,true);t.setBackgroundColor(Color.rgb(235,242,248));t.setPadding(dp(12),dp(10),dp(12),dp(10));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));t.setLayoutParams(p);return t;}
    private TextView notice(String value,int color){TextView t=text(value,16,Color.WHITE,true);t.setBackgroundColor(color);t.setPadding(dp(12),dp(12),dp(12),dp(12));return t;}
    private Button action(String s,int color){Button b=new Button(this);b.setText(s);b.setTextSize(17);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackgroundColor(color);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(p);return b;}
    private Button outline(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,dp(4),0,dp(4));b.setLayoutParams(p);return b;}
    private LinearLayout dialogBox(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(20),dp(8),dp(20),0);return l;}
    private EditText input(String hint,boolean number){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(17);if(number)e.setInputType(InputType.TYPE_CLASS_NUMBER);return e;}
    private Spinner choice(String[] values){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));return s;}
    @Override protected void onDestroy(){stopTimer();super.onDestroy();}
    @Override public void onBackPressed(){if(!selectedMachine.isEmpty())showBoard();else super.onBackPressed();}
}
